config/routes.rb
Rails.application.routes.draw do
  root "properties#index"

  resources :reservations, only: [:index, :show, :destroy]
  resources :properties do
    get :reservations
  end
  post 'properties/:id', to: 'properties#reserve'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :reservations, dependent: :destroy
  belongs_to :user, optional: false
  alias_method :owner, :user
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :property
  belongs_to :user

  validates :start_date, :end_date, presence: true
  validate :start_date_cannot_be_in_past, :end_date_must_be_after_start_date
  validate :property_must_be_available

  def start_date_cannot_be_in_past
    if start_date_in_past?
      errors.add(:start_date, "must not be in the past")
    end
  end

  def end_date_must_be_after_start_date
    if end_date_after_start_date?
      errors.add(:end_date, "must not be before start date")
    end
  end

  def property_must_be_available
    if start_date.present? && end_date.present?
      if Reservation.where(property: property).
        where('end_date >= :sd and start_date <= :ed',
              sd: start_date, ed: end_date).present?
        errors.add(:property, "is not available for selected dates")
      end
    end
  end

  private

    def start_date_in_past?
      start_date.present? && start_date.to_date < Date.today
    end

    def end_date_after_start_date?
      start_date.present? &&
        end_date.present? &&
        end_date.to_date < start_date.to_date
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :properties
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy reserve reservations ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
    if search_params[:owner_properties]
      @properties = @properties.where(user: current_user)
    else
      @properties = @properties.where.not(user: current_user)
    end
    if search_params[:start_date]&.present? && search_params[:end_date]&.present?
      @properties = @properties.where('not exists (:reservations)',
                                     reservations: Reservation.where('properties.id = reservations.property_id').
                                       where('end_date >= :sd and start_date <= :ed',
                                             sd: search_params[:start_date],
                                             ed: search_params[:end_date]))
    end
    if search_params[:postal_code]&.present?
      @properties = @properties.where(postal_code: search_params[:postal_code])
    end
    @properties
  end

  # GET /properties/1 or /properties/1.json
  def show
    @reservation = Reservation.new
    @property
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
    unless user_signed_in? && @property.user == current_user
      redirect_to @property
    end
  end

  # POST /properties or /properties.json
  def create
    # @property = Property.new(property_params)
    @property = current_user.properties.build(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if user_signed_in? && @property.owner == current_user
        if @property.update(property_params)
          format.html { redirect_to @property, notice: "Property was successfully updated." }
          format.json { render :show, status: :ok, location: @property }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @property.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @property, alert: "Unauthorized to update property."}
        format.json { render :show, status: :unauthorized, location: @property }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    respond_to do |format|
      if user_signed_in? && @property.owner == current_user
        @property.destroy
        format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { redirect_to properties_url, alert: "Unauthorized to delete property."}
        format.json { render :show, status: :unauthorized, location: @property }
      end
    end
  end

  # POST /properties/1
  def reserve
    @reservation = current_user.reservations.build(reservation_params)
    @reservation.property = @property
    respond_to do |format|
      if @reservation.save
        @reservations = current_user.reservations
        format.html { redirect_to @reservation, notice: "Reservation was successfully created." }
        format.json { render :index, status: :created, location: @reservation }
      else
        format.html { render :show, status: :unprocessable_entity, location: @property }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /properties/1/reservations
  def reservations
    if user_signed_in? && @property.owner == current_user
      @reservations = @property.reservations
      respond_to do |format|
        format.html { render 'reservations/index', status: :ok }
        format.json { render json: @reservations }
      end
    else
      redirect_to properties_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      begin
        id = params[:id] || params[:property_id]
        @property = Property.find(id)
      rescue ActiveRecord::RecordNotFound
        redirect_to action: "index"
      end
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:address_line_1, :address_line_2, :city, :state, :postal_code, :description)
    end

    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date)
    end

    def search_params
      params.permit(:start_date, :end_date, :postal_code, :owner_properties)
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all.where(user_id: current_user.id)
  end

  # GET /reservations/1 or /reservations/1.json
  def show
    redirect_to reservations_path
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    respond_to do |format|
      if current_user == @reservation.user || current_user == @reservation.property.owner
        @reservation.destroy
        format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { redirect_to reservations_url, alert: "Unauthorized to cancel reservation."}
        format.json { render :show, status: :unauthorized, location: @reservation }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      begin
        @reservation = Reservation.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to reservation_path
      end
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReservationBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Properties', properties_path, :class => 'navbar-link' %> |
      <%= link_to 'Reservations', reservations_path, :class => 'navbar-link' %> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address_line_1 %>
    <%= form.text_field :address_line_1 %>
  </div>

  <div class="field">
    <%= form.label :address_line_2 %>
    <%= form.text_field :address_line_2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_reservation_form.html.erb
<%= form_with(model: reservation, url: property_path(@property)) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_search_form.html.erb
<%= form_tag(properties_path, method: :get) do %>
  My Properties:
  <% if params[:owner_properties] %>
    <%= check_box_tag(:owner_properties, value=1, checked=true) %>
  <% else %>
    <%= check_box_tag(:owner_properties, value=1, checked=false) %>
  <% end %>
  <br/>
  <%= text_field_tag(:postal_code, params[:postal_code], placeholder: 'Zip Code') %>
  <%= date_field_tag(:start_date, params[:start_date]) %> -
  <%= date_field_tag(:end_date, params[:end_date]) %>
  <%= submit_tag("Search", :name => nil) %>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<%= render 'search_form' %>

<table>
  <thead>
    <tr>
      <th>Address line 1</th>
      <th>City</th>
      <th>State</th>
      <th>Postal code</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.address_line_1 %></td>
        <td><%= property.city %></td>
        <td><%= property.state %></td>
        <td><%= property.postal_code %></td>
        <td><%= property.description %></td>
        <td><%= link_to 'Show', property %></td>
        <% if params[:start_date]&.present? && params[:end_date]&.present? %>
          <td>
            <%= form_tag(property_path(property, reservation: { start_date: params[:start_date], end_date: params[:end_date] }), method: :post) do %>
              <%= submit_tag("Reserve", :name => nil) %>
            <% end %>
          </td>
        <% end %>
        <% if current_user == property.owner %>
          <td><%= link_to 'Reservations', property_reservations_path(property) %></td>
          <td><%= link_to 'Edit', edit_property_path(property) %></td>
          <td><%= link_to 'Delete', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address line 1:</strong>
  <%= @property.address_line_1 %>
</p>

<% if !@property.address_line_2.empty? %>
  <p>
    <strong>Address line 2:</strong>
    <%= @property.address_line_2 %>
  </p>
<% end %>

<p>
  <strong>City:</strong>
  <%= @property.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @property.state %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @property.postal_code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<%= render 'reservation_form', reservation: @reservation, property: @property %>

<% if current_user == @property.owner %>
  <%= link_to 'Edit', edit_property_path(@property) %> |
<% end %>
<%= link_to 'Back', properties_path %>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Contact</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= mail_to reservation.user.email %></td>
        <td><%= reservation.start_date.to_date %></td>
        <td><%= reservation.end_date.to_date %></td>
        <td><%= link_to 'Property', reservation.property %></td>
        <td><%= link_to 'Cancel', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>